apiVersion: batch/v1
kind: Job
metadata:
  name: collector-job
  namespace: opentelemetry-operator-system
spec:
  template:
    metadata:
      name: inspect
    spec:
      serviceAccountName: opentelemetry-operator-controller-manager
      containers:
        - name: inspect
          image: opamp-client:3
          imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4